<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>The Extended Integer (XInt) Library: Exceptions and the \c nothrow_integer type.</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.6.3 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="navpath"><a class="el" href="index.html">The Extended Integer (XInt) Library</a>
  </div>
</div>
<div class="contents">


<h1><a class="anchor" id="exceptions">Exceptions and the <code>nothrow_integer</code> type. </a></h1><p>Many things can go wrong while operating on an integer, such as divide-by-zero errors. Under normal circumstances, these result in exceptions. But exceptions sometimes make your code harder to follow, or even harder to write. That's why this library includes the <code>nothrow_integer</code> type.</p>
<p>The <code>nothrow_integer</code> type acts like a wrapper around the standard integer type, and has all of the functions that the standard type does (though a few are, of necessity, prefixed with <code>nothrow_</code>). When you use it, any exceptions generated by the library are caught internally, and the function returns a special value indicating failure (most often the <a class="el" href="nan.html">Not-a-Number</a> value).</p>
<p>Here's an example, which can be found in the <code>examples</code> subdirectory as exceptions.cpp:</p>
<div class="fragment"><pre class="fragment">
<span class="preprocessor">#include &lt;<a class="code" href="xint_8hpp.html" title="This is the include-everything header.">boost/xint/xint.hpp</a>&gt;</span>
<span class="preprocessor">#include &lt;ostream&gt;</span>

<span class="keywordtype">int</span> main() {
    <span class="keyword">using namespace </span>std;
    <span class="keyword">using namespace </span>boost::xint;

    <span class="comment">// We&#39;ll wrap this in a try block for demonstration purposes, just to</span>
    <span class="comment">// prove that it doesn&#39;t throw an exception. You normally don&#39;t need a</span>
    <span class="comment">// try block if you&#39;re using nothrow_integers.</span>
    <span class="keywordflow">try</span> {
        <span class="comment">// Call the function(s) that may produce errors. The example call tries</span>
        <span class="comment">// to interpret an empty string as an integer, which would normally</span>
        <span class="comment">// throw an xint::exception::invalid_digit.</span>
        nothrow_integer n = nothrow_integer(<span class="stringliteral">&quot;&quot;</span>);

        <span class="comment">// n should be Not-a-Number, because there was an error but exceptions</span>
        <span class="comment">// are not allowed on nothrow_integers. This example code is fairly</span>
        <span class="comment">// useless, but it shows how to test for errors.</span>
        <span class="keywordflow">if</span> (n.is_nan()) {
            cout &lt;&lt; <span class="stringliteral">&quot;n is Not-a-Number, do some intelligent error handling here.&quot;</span>
                &lt;&lt; endl;
        } <span class="keywordflow">else</span> {
            <span class="comment">// This example code should never get to this block, but you would</span>
            <span class="comment">// usually put the normal program flow code here.</span>
            cout &lt;&lt; <span class="stringliteral">&quot;Error, n should be Not-a-Number and it isn&#39;t!&quot;</span> &lt;&lt; endl;
        }
    } <span class="keywordflow">catch</span> (std::exception&amp; e) {
        <span class="comment">// This example code should never get to this block, because exceptions</span>
        <span class="comment">// were blocked.</span>
        cout &lt;&lt; <span class="stringliteral">&quot;Error, nothrow_integer threw an exception!\n&quot;</span> &lt;&lt; e.what() &lt;&lt;
            endl;
    }
}
</pre></div> </div>
<hr class="footer"/><address style="text-align: right;"><small>Generated on Sat Apr 17 20:02:58 2010 for The Extended Integer (XInt) Library by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
